version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./run.py:/app/run.py
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  # Redis service can be added later for Celery
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

  # PostgreSQL/Supabase can be added later
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=automation
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

# volumes:
#   redis-data:
#   postgres-data: 