services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - WEBHOOK_API_KEY=${WEBHOOK_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ENVIRONMENT=production
      
      # Google Calendar Configuration
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DAILY_SYNC_HOUR=${DAILY_SYNC_HOUR}
      - DAILY_SYNC_TIMEZONE=${DAILY_SYNC_TIMEZONE}
      - MAX_GOOGLE_ACCOUNTS=${MAX_GOOGLE_ACCOUNTS}
      - MAX_SYNC_FLOWS=${MAX_SYNC_FLOWS}
      
      # Google Account 1
      - GOOGLE_ACCOUNT_1_EMAIL=${GOOGLE_ACCOUNT_1_EMAIL}
      - GOOGLE_ACCOUNT_1_CLIENT_ID=${GOOGLE_ACCOUNT_1_CLIENT_ID}
      - GOOGLE_ACCOUNT_1_CLIENT_SECRET=${GOOGLE_ACCOUNT_1_CLIENT_SECRET}
      - GOOGLE_ACCOUNT_1_REFRESH_TOKEN=${GOOGLE_ACCOUNT_1_REFRESH_TOKEN}
      
      # Google Account 2
      - GOOGLE_ACCOUNT_2_EMAIL=${GOOGLE_ACCOUNT_2_EMAIL}
      - GOOGLE_ACCOUNT_2_CLIENT_ID=${GOOGLE_ACCOUNT_2_CLIENT_ID}
      - GOOGLE_ACCOUNT_2_CLIENT_SECRET=${GOOGLE_ACCOUNT_2_CLIENT_SECRET}
      - GOOGLE_ACCOUNT_2_REFRESH_TOKEN=${GOOGLE_ACCOUNT_2_REFRESH_TOKEN}
      
      # Sync Flow 1
      - SYNC_FLOW_1_NAME=${SYNC_FLOW_1_NAME}
      - SYNC_FLOW_1_SOURCE_ACCOUNT_ID=${SYNC_FLOW_1_SOURCE_ACCOUNT_ID}
      - SYNC_FLOW_1_SOURCE_CALENDAR_ID=${SYNC_FLOW_1_SOURCE_CALENDAR_ID}
      - SYNC_FLOW_1_TARGET_ACCOUNT_ID=${SYNC_FLOW_1_TARGET_ACCOUNT_ID}
      - SYNC_FLOW_1_TARGET_CALENDAR_ID=${SYNC_FLOW_1_TARGET_CALENDAR_ID}
      - SYNC_FLOW_1_START_OFFSET=${SYNC_FLOW_1_START_OFFSET}
      - SYNC_FLOW_1_END_OFFSET=${SYNC_FLOW_1_END_OFFSET}
      
      # Sync Flow 2
      - SYNC_FLOW_2_NAME=${SYNC_FLOW_2_NAME}
      - SYNC_FLOW_2_SOURCE_ACCOUNT_ID=${SYNC_FLOW_2_SOURCE_ACCOUNT_ID}
      - SYNC_FLOW_2_SOURCE_CALENDAR_ID=${SYNC_FLOW_2_SOURCE_CALENDAR_ID}
      - SYNC_FLOW_2_TARGET_ACCOUNT_ID=${SYNC_FLOW_2_TARGET_ACCOUNT_ID}
      - SYNC_FLOW_2_TARGET_CALENDAR_ID=${SYNC_FLOW_2_TARGET_CALENDAR_ID}
      - SYNC_FLOW_2_START_OFFSET=${SYNC_FLOW_2_START_OFFSET}
      - SYNC_FLOW_2_END_OFFSET=${SYNC_FLOW_2_END_OFFSET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis service can be added later for Celery
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

  # PostgreSQL/Supabase can be added later
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=automation
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

# volumes:
#   redis-data:
#   postgres-data: 